### ISSUE TITLE
Quorum runs with max thread

### ISSUE THREAD

**Issue by macmanes** [sreeramkannan/Shannon#10]
Using a clone from the develop branch (pulled this AM), Quorum is using the all the threads on the server, even tho I'm only asking for 20 threads. Not sure if this is a Quorum bug or a Shannon bug. 

```
time python /share/Shannon/shannon.py -p20 \
-o shannon_trin_SS  \
--left /mouse/trin_mouse/mouse.all.Left.fq  \
--right /mouse/trin_mouse/mouse.all.Right.fq -ss
```

From `top`

```
/share/quorum/bin/quorum_error_correct_reads -t 64 -o /mouse/shannon/shannon_trin_SS/quorum_output /mouse/shannon/shannon_trin_SS/quorum_output_mer_database.jf ...
```

**Comment by sreeramkannan** [comment]
1. Thanks for pointing out the bug. The flag for -p was not fed through to
   Quorum properly. This bug is fixed now in the latest commit on develop
   branch.
2. The flag for single stranded is "--ss"  not "-ss"
   (I am not sure which is more standard notation).

**Comment by macmanes** [comment]
I think convention would be`-s` or `--strand_specific` or whatever for the long option. really tho, this is my typo. What I will say, is that unrecognized options should fail with immediate error, no?

**Comment by sreeramkannan** [comment]
1. Updated to -s or --strand_specific for parsing that option.
2. In the updated version, the option parser will mention which options
   have been utilized to do what and which options have been rejected.

Thanks a ton for your comments!

**Comment by sreeramkannan** [comment]
These options are now available on Master. Thanks for your feedback.
