### ISSUE TITLE
Error during run

### ISSUE THREAD

**Issue by peterdfields** [sreeramkannan/Shannon#12]
Using the most recent master version Shannon I get the following error:

Thu Mar 31 16:37:04 2016: gpmetis for partitioning is complete
 Component 0: 100 partitions,
Thu Mar 31 16:42:07 2016: k1mers2component dictionary created
Traceback (most recent call last):
  File "/TowerData/home/peter/bioinformatics/shannon/shannon.py", line 342, in <module>
    [components_broken, new_components] = kmers_for_component(k1mer_dictionary,kmer_directory, reads_files, base_directory_name, contig_file_extension, get_partition_kmers, double_stranded, paired_end, use_second_iteration, partition_size, overload, K, gpmetis_path, penalty, only_reads)
  File "/TowerData/home/peter/bioinformatics/shannon/kmers_for_component.py", line 272, in kmers_for_component
    read1_reversed = reverse_complement(read1)
  File "/TowerData/home/peter/bioinformatics/shannon/kmers_for_component.py", line 26, in <lambda>
    reverse_complement = lambda x: ''.join([{'A':'T','C':'G','G':'C','T':'A'}[B] for B in x][::-1])
KeyError: 'N'

Please let me know what additional info might be useful.

**Comment by sreeramkannan** [comment]
Thanks for using Shannon and reporting the bug.
1. This is due to a recent speed-up of reverse complement unable to handle
   'N' nucleotides in the reads. I will release a fix soon (later today
   addressing this issue).

Thanks for your help!
Sreeram

**Comment by peterdfields** [comment]
Thanks!

**Comment by sreeramkannan** [comment]
Updated to deal with non-ACTG reads.
Thanks for your feedback. Please let me know if it works now.

**Comment by sreeramkannan** [comment]
Updated to deal with non-ACTG reads.

Thanks for your feedback. Please let me know if it works now.
