### ISSUE TITLE
tag a release

### ISSUE THREAD

**Issue by mes5k** [sreeramkannan/Shannon#15]
Any chance of getting a tagged release of Shannon so that we can use a consistent version?

**Comment by sreeramkannan** [comment]
Yes, we will have a tagged release soon (in a week or so).

Thanks for trying out Shannon!
Sreeram

**Comment by mes5k** [comment]
Awesome, thanks!

**Comment by sreeramkannan** [comment]
There is a tagged release of Shannon now.

Thanks for trying out Shannon!
Sreeram

**Comment by mes5k** [comment]
Perfect, thanks for you efforts!
