### ISSUE TITLE
unexpected output in rc_s.py

### ISSUE THREAD

**Issue by derekmorr** [sreeramkannan/Shannon#24]
I'm seeing unexpected output from rc_s.py. It's processing each line one at a time, instead of processing the sequence as a whole. So the output has the lines in their original order, with the contents of each line reversed. But I think the program should reverse the sequence.

For example, given this input:
```
GTTTATTCAAACTTAGATACAGATGAAGAATAAGAATGTTCATATGCAAGAAATATTTTTTTCTTATTAT
TATATGTACAATACATTCTTTATGCTCTTACTTTCAAATGTTTCTAATTAAATGAGAGAAAGCCTATATT
CGATCTCGTTTCTAATGTATATTGTTTGTATTTCCTTTTACATATCAGATCTCTTGAATC
```

I would expect this output:
```
GATTCAAGAGATCTGATATGTAAAAGGAAATACAAACAATATACATTAGAAACGAGATCGAATATAGGCT
TTCTCTCATTTAATTAGAAACATTTGAAAGTAAGAGCATAAAGAATGTATTGTACATATAATAATAAGAA
AAAAATATTTCTTGCATATGAACATTCTTATTCTTCATCTGTATCTAAGTTTGAATAAAC
```

But I'm actually getting this:

```
ATAATAAGAAAAAAATATTTCTTGCATATGAACATTCTTATTCTTCATCTGTATCTAAGTTTGAATAAAC
AATATAGGCTTTCTCTCATTTAATTAGAAACATTTGAAAGTAAGAGCATAAAGAATGTATTGTACATATA
GATTCAAGAGATCTGATATGTAAAAGGAAATACAAACAATATACATTAGAAACGAGATCG
```

**Comment by bx3** [comment]
Hello,

I believe Shannon expects single-line fasta input for majority of its code. So the simplest way to solve it is just converting multi-line input to single-line by using command:

awk '/^>/ {printf("\n%s\n",$0);next; } { printf("%s",$0);}  END {printf("\n");}' < input | tail -n +2 > output

where you specify input and output.

**Comment by derekmorr** [comment]
That awk command just removes the newlines. It doesn't address the issue that the sequence isn't being reversed properly. I think rc_s.py needs to buffer the sequence and compute the rc.

As an aside, I've been looking into rewriting parts of Shannon in rust. I rewrote rc_s.py and got an 8x speedup on several sample files. Is this something the maintainers would be interested in exploring?

**Comment by derekmorr** [comment]
Oh, my apologies. You meant to run awk before running `rc_s.py`. Yes, that would fix the issue.

**Comment by bx3** [comment]
Great that it helps. Actually, we have been converting everything into C++ since last year, and it is nearly complete. Both memory and speed performance improve a lot, and we will release them once they are ready.

**Comment by derekmorr** [comment]
Is the c++ code available on a branch in a repo somewhere?

**Comment by bx3** [comment]
Yes, it is under my repo at https://github.com/bx3/Shannon_Cpp_RNA_seq, and I am reviewing it now.

**Comment by macmanes** [comment]
That link is broken.

**Comment by bx3** [comment]
C++ code is completed, and now release at 
https://github.com/bx3/Shannon_Cpp_RNA_seq/wiki
