### ISSUE TITLE
KeyError: '\x1f'

### ISSUE THREAD

**Issue by awata-hiroko** [sreeramkannan/Shannon#28]
Hi,

Does anyone have any thought on the below error that came up using my original data when I did shannon? I completed it with no error using test data in the shannon/Samples directory. 

`Thu Oct 10 13:24:20 2019: Starting Shannon run..
Traceback (most recent call last):
  File "/home/***/Shannon/rc_s.py", line 35, in <module>
    main()
  File "/home/***/Shannon/rc_s.py", line 30, in main
    reverse_complement_serial(infile, outfile)
  File "/home/***/Shannon/rc_s.py", line 16, in reverse_complement_serial
    reads.append(reverse_complement(fields[0]))
  File "/home/***/Shannon/rc_s.py", line 3, in <lambda>
    reverse_complement = lambda x: ''.join([D[B] for B in x][::-1])
KeyError: '\x1f'
cat: /datadrive/***/Assemble/Shannon/test_all/test_all_algo_input/rc.fasta: No such file or directory
/bin/rm: cannot remove '/datadrive/Assemble/Shannon/test_all/test_all_algo_input/rc.fasta': No such file or directory
Processed No of reads:3510991, Avg. Read length: 265.984430891
Thu Oct 10 13:24:23 2019: Starting Jellyfish to extract Kmers from Reads..
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unsupported format
Aborted (core dumped)
Failed to open input file '/datadrive/***/Assemble/Shannon/test_all/test_all_algo_input/jellyfish_p1_output.jf'
Thu Oct 10 13:24:24 2019: Jellyfish finished..
nJobs:1
reads_files:/datadrive/***/Assemble/Shannon/test_all/test_all_algo_input/reads.fasta
Thu Oct 10 13:24:24 2019: Starting Kmer error correction..
Traceback (most recent call last):
  File "/home/***/Shannon/shannon.py", line 459, in <module>
    k1mer_dictionary,reads = extension_correction(str_ec.split(),dontWriteToFile)
  File "/home/***/Shannon/extension_correction.py", line 548, in extension_correction
    allowed_kmer_dict, reads = run_correction(infile, outfile, min_weight, min_length, double_stranded, comp_directory_name, comp_size_threshold, True, inMem, nJobs, reads_files)
  File "/home/***/Shannon/extension_correction.py", line 317, in run_correction
    kmers, K = load_kmers(infile, double_stranded,polyA_del)
  File "/home/***/Shannon/extension_correction.py", line 220, in load_kmers
    K = len(kmers.keys()[0])
IndexError: list index out of range`

**Comment by bx3** [comment]
Happy to know that the issue is solved. Just want to mention that we have a newer and faster version at 
https://github.com/bx3/Shannon_Cpp_RNA_seq.

Edit:
I see. it is not solved; I will take a look on the other thread.
